version: '3.4'

services:
  weatherapi:
    image: weatherapi:dev
    container_name: WeatherAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WeatherAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_weatherapi$
    volumes:
      - C:\Users\Kehinde Aregbesola\Desktop\interview questions and answers\Weather-API\WeatherAPI:/app
      - C:\Users\Kehinde Aregbesola\Desktop\interview questions and answers\Weather-API:/src
      - C:\Users\Kehinde Aregbesola\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_weatherapi$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_weatherapi$ \"/app/bin/Debug/net6.0/WeatherAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true